---
title: "GenBank California"
author: ""
output: 
  html_document
runtime: shiny
---

```{r setup, message = F, warning = F, echo = F}
library(tidyverse)
library(knitr)
library(mapview)
library(shiny)
library(leaflet)
library(shinyWidgets)
library(sf)
library(here)

# global chunk options
opts_chunk$set(warning = FALSE, message = FALSE, eval = T, echo = F)

# for mapshot on shinyapps
if (is.null(suppressMessages(webshot:::find_phantom()))) { webshot::install_phantomjs() }

# rmd downloads
downloadButtonRmd <- function (outputId, label = "Download", class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}

# data
dat <- read.csv(here('data', 'rawdat.csv'), stringsAsFactors = F) %>% 
  st_as_sf(coords = c('pr2_longitude', 'pr2_latitude'), crs = 4326)

# map types
mptyps <- c("CartoDB.Positron", "CartoDB.DarkMatter", "OpenStreetMap", "Esri.WorldImagery", "OpenTopoMap")

```

```{r topselectors}

column(width = 12,
       
  column(width = 4,
        
        # select metric type
        selectInput("fltby", "Select taxonomic filter type:", choices = c('kingdom', 'supergroup', 'division', 'class', 'order', 'family', 'genus', 'species', 'gene', 'gb_collection_date', 'gb_collected_by', 'pr2_sample_type'), selected = 'supergroup')
  
  ),
  
  column(width = 4, 
        
        renderUI({
          
          # input
          fltby <- input$fltby
          
          # pull metrics to select based on input
          tosel <- dat %>%
            pull(!!fltby) %>% 
            unique
        
          # select watershed
          pickerInput("flts", label = 'Select filter(s):', choices = tosel,
            options = list(`actions-box` = TRUE, size = 20), selected = tosel, multiple = TRUE)
          
        })
        
  ) 
)
```

```{r, reactives}
# filtered data 
gendat <- reactive({
  
  # inputs
  fltby <- input$fltby
  flts <- input$flts
  
  req(flts)
  
  flt <- dat %>% 
    pull(!!fltby) 
    
  out <- dat %>% 
    filter(flt %in% flts)
  
  return(out)
  
})

# map
genmap <- reactive({
  
  # input
  gendat <- gendat()
  
  validate(
    need(nrow(gendat) > 0, 'No data selected')
  )
  
  out <- mapview(gendat, homebutton = F, color = 'black', zcol = 'pr2_sample_type', alpha = 0.9, 
                 map.types = mptyps, layer = 'pr2_sample_type')
  
  return(out)
  
})
```

```{r, downloadhandlers}
# map for observed species
output$dlgenmap <- downloadHandler(
  filename = function(){'genmap.png'},
  content = function(file){
    mapshot(x = genmap(), file = file)
  }
)

# data filtered data
output$dlgendat <- downloadHandler(
  filename = function(){'gendat.csv'},
  content = function(file){
    browser()
    crds <- st_coordinates(gendat()) %>% 
      data.frame
    names(crds) <- c('pr2_longitude', 'pr2_latitude')
    todl <- gendat() %>% 
      st_set_geometry(NULL) %>% 
      data.frame %>% 
      dplyr::bind_cols(., crds)
    write.csv(todl, file, quote = T, row.names = F)
  }
)
```

```{r, mapoutput}
output$genmap <- renderLeaflet({genmap()@map})
output$gentab <- renderDataTable({gendat()})
```

# {.tabset}

## Map

```{r}
column(12, 
  column(4, downloadButtonRmd('dlgenmap', 'Download map'))
  )
column(12, 
  leafletOutput('genmap', height = 700)
)

```

## Table

```{r}
column(12, 
  column(4, downloadButtonRmd('dlgentab', 'Download table'))
  )
shiny::dataTableOutput('gentab')
```

